### ISSUE TITLE
emmmmmm

### ISSUE THREAD

**Issue by Lakr233** [zanjie1999/make_lrc_music_m3u#1]
File "/Users/qaq/Desktop/make_lrc_music_m3u-master/make_lrc_music_m3u.py", line 234
    print("\r" + str(nowNum) + '/ ' + str(allNum), end=' ')

both 2 3

**Comment by zanjie1999** [comment]
使用exe的版本吧，为什么我这里这句挺正常的....

我实在是没能明白为什么你那会出这种错XD

**Comment by zanjie1999** [comment]
今天突然发现使用python2运行就会返回这个错误，请使用真正的python3（
