### ISSUE TITLE
现在网易云官方只能获取歌单前几首了...

### ISSUE THREAD

**Issue by NOAME18** [zanjie1999/make_lrc_music_m3u#2]
能不能用cookie之类的办法解决
![image](https://user-images.githubusercontent.com/53110680/89763775-c72b5480-db25-11ea-90b9-c80b06d161e9.png)

**Comment by zanjie1999** [comment]
能，但是怕被ban号，不过不管用不用功能必须有，晚上开个小号来试一下吧（

**Comment by zanjie1999** [comment]
```
......

# 账号cookie 
# 由于不登录只会返回前10首歌 更多的需要登录 建议用小号 别人得到了这段cookie相当于能登录你的账号 请务必不要泄露
# Chrome打开网抑云 -> 登录 -> 按F12打开 开发者工具 -> 切换到 Console -> 输入 document.cookie 按回车 -> 复制输出内容替换下面的双引号
cookie = ""

......
```

搞定，多了一个设置参数，实测静态歌单ok，动态歌单（比如私人雷达）实测不行

另外更新了最新的头部避免被ban

那我就close啦XD

**Comment by NOAME18** [comment]
感谢，不过测试了一下貌似加cookie之后只是多了10首...我的喜欢歌单有2000多首...感觉现在网易云好坑啊..我只是想备份歌单而已...
![image](https://user-images.githubusercontent.com/53110680/89814059-25335880-db75-11ea-9e5c-b38c67b284ff.png)

**Comment by zanjie1999** [comment]
巧了，用来测试的歌单刚好就是20首的QAQ
